In [1]:
import numpy as np
import pandas as pd
import os
from datetime import datetime, date
from statsmodels.tsa.vector_ar.var_model import VAR
from statsmodels.tsa.vector_ar.vecm import VECM
import scipy.linalg as la
from scipy.linalg import eig
from statsmodels.tsa.vector_ar.var_model import VAR
import statsmodels.api as sm
print(f"modules have been imported.")

modules have been imported.

In [3]:
# Step 1: Lets grab the historical time series from Mohaddes first. 
# Question should we grab it by economies first? if yes then lets take the 'Country Data'
print(os.getcwd())
target_filename = "Country Data (1979Q2-2023Q3).xls"
target_file_path = os.getcwd() + "\\" + "GVAR Database (1979Q2-2023Q3)\\" + target_filename
print(f"target_file_path is: {target_file_path}")
# dataframe the country data
countries_df = pd.read_excel(target_file_path, sheet_name = None)
countries_df.keys()

C:\Users\benchee
target_file_path is: C:\Users\benchee\GVAR Database (1979Q2-2023Q3)\Country Data (1979Q2-2023Q3).xls

dict_keys(['ARGENTINA', 'AUSTRALIA', 'BRAZIL', 'CANADA', 'CHINA', 'CHILE', 'EURO', 'INDIA', 'INDONESIA', 'JAPAN', 'KOREA', 'MALAYSIA', 'MEXICO', 'NORWAY', 'NEW ZEALAND', 'PERU', 'PHILIPPINES', 'SOUTH AFRICA', 'SAUDI ARABIA', 'SINGAPORE', 'SWEDEN', 'SWITZERLAND', 'THAILAND', 'TURKEY', 'UNITED KINGDOM', 'USA'])

In [4]:
us_df = countries_df['USA']
# convert the date into datetime format 
# ie: 1979Q2 is 30-Jun-1979.
us_df['date_2'] = pd.PeriodIndex(us_df['date'], freq = 'Q').to_timestamp(how = "end").date

target_cols = [col for col in us_df.columns if 'date' not in col]
target_cols = ['date_2'] + target_cols 
print(target_cols)
us_df = us_df[target_cols]
us_df = us_df.rename(columns={'date_2': 'date'})
us_df

['date_2', 'y', 'Dp', 'eq', 'r', 'lr', 'ys', 'Dps', 'eps', 'poil', 'pmat', 'pmetal']

,date,y,Dp,eq,r,lr,ys,Dps,eps,poil,pmat,pmetal
0,1979-06-30,3.960503,0.033730,0.684670,0.022407,0.021804,3.723439,0.027880,-2.381442,3.433544,4.148960,4.200168
1,1979-09-30,3.967677,0.032477,0.699070,0.023084,0.021781,3.736803,0.029817,-2.420323,3.576322,4.272871,4.198063
2,1979-12-31,3.970622,0.028823,0.640953,0.027982,0.024841,3.755427,0.029535,-2.440535,3.696729,4.220098,4.305733
3,1980-03-31,3.973806,0.038217,0.615193,0.031335,0.028302,3.766682,0.040626,-2.465478,3.661658,4.311326,4.431295
4,1980-06-30,3.953413,0.035451,0.609975,0.022955,0.024909,3.768565,0.033697,-2.498637,3.643353,4.207531,4.284341
...,...,...,...,...,...,...,...,...,...,...,...,...
173,2022-09-30,5.008861,0.014444,2.906448,0.006571,0.007648,5.331930,0.014947,-3.370713,4.613407,4.814593,5.240803
174,2022-12-31,5.015219,0.009122,2.961698,0.009901,0.009396,5.332679,0.011538,-3.365033,4.485170,4.719217,5.244402
175,2023-03-31,5.018379,0.010911,3.020958,0.011307,0.008954,5.343477,0.008314,-3.395617,4.397714,4.696997,5.416306
176,2023-06-30,5.029266,0.004715,3.095903,0.012372,0.008826,5.352381,0.007976,-3.403638,4.361766,4.674107,5.315188
177,2023-09-30,5.041832,0.009635,3.051312,0.012887,0.010165,5.356727,0.010715,-3.408446,4.462956,4.678431,5.289791

In [7]:
# 1. This is to test the weak exogeneity for each variable components in the us_df table. 
# 2. We need to do the AIC and BIC test to find out the lags that are most optimal for the VARX

p,q are: (1,0)
p,q are: (1,1)
p,q are: (1,2)
p,q are: (2,0)
p,q are: (2,1)
p,q are: (2,2)
p,q are: (3,0)
p,q are: (3,1)
p,q are: (3,2)

In [8]:
# to run the VARX model.
# After running the weak exogeneity test, we will then proceed to run the VARX for
# the variables are do not violate the weak exogeneity test. 
endog_vars = ['y', 'Dp', 'eq', 'r', 'lr', 'poil', 'pmat', 'pmetal']
exog_vars = ['ys', 'Dps']

us_endog_df = us_df[endog_vars]
us_exog_df = us_df[exog_vars]

display(us_endog_df)
display(us_exog_df)

# lets assume that our lags are as follows p_{domestic} = 2, q_{foreign} = 1
# so we are now finding for VAR(p, q) = VAR(2, 1)
# so for our exog data we need to start at iloc[1:] as our t 
# and shift(1).iloc[1:] as our t - 1
# for endog_data we will start at us_df.iloc[2:] as our t 
# and us_df.shift(1).iloc[2:] as our t - 2
p, q = 2, 1

# to define the exog data here based on lags (defined by AIC/BIC/HQIC) and shifts (based on also lags?).
us_exog_contemp_df = us_exog_df.iloc[p:] # align to match the loss of 2 domestic lags.
us_exog_lag1_df = us_exog_df.shift(1).iloc[p:]
display(us_exog_contemp_df)
display(us_exog_lag1_df)
print(f"us_exog_df shift(1) is: {display(us_exog_df.shift(1))}")
print(f"us_exog_df shift(1).iloc[p:] is: {display(us_exog_df.shift(1).iloc[p:])}")

# Concatenate the exog data here with the shifts and lags. 
us_exog_final_df = pd.concat([us_exog_contemp_df, us_exog_lag1_df], axis = 1)
print(f"us_exog_final_df is: {display(us_exog_final_df)}")
col_names = [f"{col}_lag1" for col in us_exog_df.columns]
all_col_exog_names = us_exog_df.columns.tolist() + col_names
print(all_col_exog_names)
# This is to ensure that the naming convention for the lags and the contemporary data are defined correctly.
us_exog_final_df.columns = all_col_exog_names
print(f"us_exog_final_df is: {display(us_exog_final_df)}")

# Add in the constant from the exog data. 
us_exog_final_df = sm.add_constant(us_exog_final_df)
print(f"us_exog_final_df after including constant is: {display(us_exog_final_df)}")

# define us endogeneous data
us_endog_final_df = us_endog_df.iloc[p:]
display(us_endog_final_df)

# Fit the level VARX model via statsmodels 
# we used maxlags = max(p,q) for the domestic variables and passing foreign vectors as exog.
varx_model = VAR(endog = us_endog_final_df, exog = us_exog_final_df)
varx_results = varx_model.fit(maxlags = p)

print(f"--- US VARX({p},{q}) Model Estimated Successfully ---")
print(f"Endogenous Matrix Dimensions (Variables): {us_endog_final_df.shape[1]}")
print(f"Exogenous Matrix Dimensions (Regressors): {us_exog_final_df.shape[1]}")
print(f"\nCoefficient Parameters shape for the US system:", varx_results.params.shape)
print(varx_results.summary())

,y,Dp,eq,r,lr,poil,pmat,pmetal
0,3.960503,0.033730,0.684670,0.022407,0.021804,3.433544,4.148960,4.200168
1,3.967677,0.032477,0.699070,0.023084,0.021781,3.576322,4.272871,4.198063
2,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733
3,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295
4,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341
...,...,...,...,...,...,...,...,...
173,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803
174,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402
175,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306
176,5.029266,0.004715,3.095903,0.012372,0.008826,4.361766,4.674107,5.315188
177,5.041832,0.009635,3.051312,0.012887,0.010165,4.462956,4.678431,5.289791

           ys       Dps
0    3.723439  0.027880
1    3.736803  0.029817
2    3.755427  0.029535
3    3.766682  0.040626
4    3.768565  0.033697
..        ...       ...
173  5.331930  0.014947
174  5.332679  0.011538
175  5.343477  0.008314
176  5.352381  0.007976
177  5.356727  0.010715

[178 rows x 2 columns]

           ys       Dps
2    3.755427  0.029535
3    3.766682  0.040626
4    3.768565  0.033697
5    3.776422  0.032422
6    3.787429  0.032043
..        ...       ...
173  5.331930  0.014947
174  5.332679  0.011538
175  5.343477  0.008314
176  5.352381  0.007976
177  5.356727  0.010715

[176 rows x 2 columns]

           ys       Dps
2    3.736803  0.029817
3    3.755427  0.029535
4    3.766682  0.040626
5    3.768565  0.033697
6    3.776422  0.032422
..        ...       ...
173  5.320754  0.021158
174  5.331930  0.014947
175  5.332679  0.011538
176  5.343477  0.008314
177  5.352381  0.007976

[176 rows x 2 columns]

           ys       Dps
0         NaN       NaN
1    3.723439  0.027880
2    3.736803  0.029817
3    3.755427  0.029535
4    3.766682  0.040626
..        ...       ...
173  5.320754  0.021158
174  5.331930  0.014947
175  5.332679  0.011538
176  5.343477  0.008314
177  5.352381  0.007976

[178 rows x 2 columns]

us_exog_df shift(1) is: None

           ys       Dps
2    3.736803  0.029817
3    3.755427  0.029535
4    3.766682  0.040626
5    3.768565  0.033697
6    3.776422  0.032422
..        ...       ...
173  5.320754  0.021158
174  5.331930  0.014947
175  5.332679  0.011538
176  5.343477  0.008314
177  5.352381  0.007976

[176 rows x 2 columns]

us_exog_df shift(1).iloc[p:] is: None

           ys       Dps        ys       Dps
2    3.755427  0.029535  3.736803  0.029817
3    3.766682  0.040626  3.755427  0.029535
4    3.768565  0.033697  3.766682  0.040626
5    3.776422  0.032422  3.768565  0.033697
6    3.787429  0.032043  3.776422  0.032422
..        ...       ...       ...       ...
173  5.331930  0.014947  5.320754  0.021158
174  5.332679  0.011538  5.331930  0.014947
175  5.343477  0.008314  5.332679  0.011538
176  5.352381  0.007976  5.343477  0.008314
177  5.356727  0.010715  5.352381  0.007976

[176 rows x 4 columns]

us_exog_final_df is: None
['ys', 'Dps', 'ys_lag1', 'Dps_lag1']

           ys       Dps   ys_lag1  Dps_lag1
2    3.755427  0.029535  3.736803  0.029817
3    3.766682  0.040626  3.755427  0.029535
4    3.768565  0.033697  3.766682  0.040626
5    3.776422  0.032422  3.768565  0.033697
6    3.787429  0.032043  3.776422  0.032422
..        ...       ...       ...       ...
173  5.331930  0.014947  5.320754  0.021158
174  5.332679  0.011538  5.331930  0.014947
175  5.343477  0.008314  5.332679  0.011538
176  5.352381  0.007976  5.343477  0.008314
177  5.356727  0.010715  5.352381  0.007976

[176 rows x 4 columns]

us_exog_final_df is: None

     const        ys       Dps   ys_lag1  Dps_lag1
2      1.0  3.755427  0.029535  3.736803  0.029817
3      1.0  3.766682  0.040626  3.755427  0.029535
4      1.0  3.768565  0.033697  3.766682  0.040626
5      1.0  3.776422  0.032422  3.768565  0.033697
6      1.0  3.787429  0.032043  3.776422  0.032422
..     ...       ...       ...       ...       ...
173    1.0  5.331930  0.014947  5.320754  0.021158
174    1.0  5.332679  0.011538  5.331930  0.014947
175    1.0  5.343477  0.008314  5.332679  0.011538
176    1.0  5.352381  0.007976  5.343477  0.008314
177    1.0  5.356727  0.010715  5.352381  0.007976

[176 rows x 5 columns]

us_exog_final_df after including constant is: None

,y,Dp,eq,r,lr,poil,pmat,pmetal
2,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733
3,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295
4,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341
5,3.951749,0.018735,0.694921,0.021896,0.025985,3.550055,4.289884,4.277811
6,3.970122,0.025836,0.724808,0.031908,0.029275,3.679337,4.284165,4.195716
...,...,...,...,...,...,...,...,...
173,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803
174,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402
175,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306
176,5.029266,0.004715,3.095903,0.012372,0.008826,4.361766,4.674107,5.315188
177,5.041832,0.009635,3.051312,0.012887,0.010165,4.462956,4.678431,5.289791

--- US VARX(2,1) Model Estimated Successfully ---
Endogenous Matrix Dimensions (Variables): 8
Exogenous Matrix Dimensions (Regressors): 5

Coefficient Parameters shape for the US system: (22, 8)
  Summary of Regression Results
==================================
Model:                         VAR
Method:                        OLS
Date:           Sun, 19, Jul, 2026
Time:                     22:29:30
--------------------------------------------------------------------
No. of Equations:         8.00000    BIC:                   -65.9803
Nobs:                     174.000    HQIC:                  -67.8794
Log likelihood:           4219.12    FPE:                9.16476e-31
AIC:                     -69.1757    Det(Omega_mle):     3.53563e-31
--------------------------------------------------------------------
Results for equation y
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.113483              NAN              NAN             NAN
const             0.113483              NAN              NAN             NAN
ys                0.752202         0.043085           17.458           0.000
Dps               0.015706         0.078656            0.200           0.842
ys_lag1          -0.715131         0.042477          -16.836           0.000
Dps_lag1          0.036118         0.079076            0.457           0.648
L1.y              0.884492              NAN              NAN             NAN
L1.Dp            -0.334006         0.117631           -2.839           0.005
L1.eq             0.023620         0.007506            3.147           0.002
L1.r              0.773397         0.351529            2.200           0.028
L1.lr            -0.233621         0.568167           -0.411           0.681
L1.poil           0.001353         0.004117            0.329           0.742
L1.pmat          -0.018913         0.011251           -1.681           0.093
L1.pmetal         0.002229         0.006379            0.349           0.727
L2.y              0.022273              NAN              NAN             NAN
L2.Dp             0.106204         0.097797            1.086           0.277
L2.eq            -0.007447         0.007771           -0.958           0.338
L2.r             -1.284228         0.342213           -3.753           0.000
L2.lr             0.720966         0.547551            1.317           0.188
L2.poil          -0.002837         0.004134           -0.686           0.492
L2.pmat           0.015682         0.011006            1.425           0.154
L2.pmetal         0.000645         0.006611            0.098           0.922
============================================================================

Results for equation Dp
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.032829              NAN              NAN             NAN
const             0.032829              NAN              NAN             NAN
ys                0.130136         0.033845            3.845           0.000
Dps               0.157967         0.061787            2.557           0.011
ys_lag1          -0.133081         0.033367           -3.988           0.000
Dps_lag1         -0.128608         0.062117           -2.070           0.038
L1.y             -0.038328              NAN              NAN             NAN
L1.Dp             0.316481         0.092402            3.425           0.001
L1.eq             0.003121         0.005896            0.529           0.597
L1.r              0.735597         0.276136            2.664           0.008
L1.lr             0.267823         0.446311            0.600           0.548
L1.poil           0.001417         0.003234            0.438           0.661
L1.pmat          -0.005169         0.008838           -0.585           0.559
L1.pmetal         0.001140         0.005011            0.227           0.820
L2.y              0.032016              NAN              NAN             NAN
L2.Dp             0.137381         0.076822            1.788           0.074
L2.eq            -0.001855         0.006105           -0.304           0.761
L2.r             -0.446999         0.268818           -1.663           0.096
L2.lr            -0.791394         0.430117           -1.840           0.066
L2.poil          -0.003679         0.003247           -1.133           0.257
L2.pmat          -0.003244         0.008645           -0.375           0.707
L2.pmetal         0.005079         0.005193            0.978           0.328
============================================================================

Results for equation eq
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.289221              NAN              NAN             NAN
const             0.289221              NAN              NAN             NAN
ys                0.535226         0.531647            1.007           0.314
Dps              -0.781948         0.970574           -0.806           0.420
ys_lag1          -0.214152         0.524145           -0.409           0.683
Dps_lag1         -0.404794         0.975758           -0.415           0.678
L1.y              0.563690              NAN              NAN             NAN
L1.Dp            -0.204049         1.451497           -0.141           0.888
L1.eq             0.903442         0.092620            9.754           0.000
L1.r              4.061233         4.337661            0.936           0.349
L1.lr           -16.116995         7.010853           -2.299           0.022
L1.poil          -0.031801         0.050805           -0.626           0.531
L1.pmat          -0.222120         0.138827           -1.600           0.110
L1.pmetal         0.119092         0.078715            1.513           0.130
L2.y             -0.878644              NAN              NAN             NAN
L2.Dp             0.196592         1.206762            0.163           0.871
L2.eq            -0.007759         0.095895           -0.081           0.936
L2.r              0.226633         4.222712            0.054           0.957
L2.lr             8.902900         6.756468            1.318           0.188
L2.poil          -0.032990         0.051007           -0.647           0.518
L2.pmat           0.176280         0.135803            1.298           0.194
L2.pmetal        -0.097154         0.081575           -1.191           0.234
============================================================================

Results for equation r
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.006490              NAN              NAN             NAN
const             0.006490              NAN              NAN             NAN
ys                0.017526         0.011545            1.518           0.129
Dps              -0.004139         0.021077           -0.196           0.844
ys_lag1          -0.017370         0.011382           -1.526           0.127
Dps_lag1          0.017677         0.021189            0.834           0.404
L1.y              0.011654              NAN              NAN             NAN
L1.Dp            -0.105667         0.031520           -3.352           0.001
L1.eq             0.002373         0.002011            1.180           0.238
L1.r              1.125326         0.094195           11.947           0.000
L1.lr             0.131122         0.152245            0.861           0.389
L1.poil           0.001304         0.001103            1.182           0.237
L1.pmat          -0.002326         0.003015           -0.771           0.440
L1.pmetal         0.001072         0.001709            0.627           0.530
L2.y             -0.014255              NAN              NAN             NAN
L2.Dp             0.135117         0.026206            5.156           0.000
L2.eq            -0.001508         0.002082           -0.724           0.469
L2.r             -0.265097         0.091699           -2.891           0.004
L2.lr            -0.091118         0.146721           -0.621           0.535
L2.poil          -0.001806         0.001108           -1.630           0.103
L2.pmat           0.001069         0.002949            0.363           0.717
L2.pmetal        -0.000194         0.001771           -0.110           0.913
============================================================================

Results for equation lr
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.011106              NAN              NAN             NAN
const             0.011106              NAN              NAN             NAN
ys                0.017344         0.008372            2.072           0.038
Dps               0.003210         0.015283            0.210           0.834
ys_lag1          -0.017605         0.008254           -2.133           0.033
Dps_lag1          0.010956         0.015365            0.713           0.476
L1.y              0.007108              NAN              NAN             NAN
L1.Dp            -0.019356         0.022856           -0.847           0.397
L1.eq             0.001362         0.001458            0.934           0.350
L1.r              0.071671         0.068304            1.049           0.294
L1.lr             1.039959         0.110398            9.420           0.000
L1.poil           0.000622         0.000800            0.778           0.437
L1.pmat          -0.003249         0.002186           -1.486           0.137
L1.pmetal         0.000469         0.001240            0.378           0.705
L2.y             -0.010508              NAN              NAN             NAN
L2.Dp             0.040176         0.019002            2.114           0.034
L2.eq            -0.001134         0.001510           -0.751           0.453
L2.r              0.001272         0.066494            0.019           0.985
L2.lr            -0.308448         0.106392           -2.899           0.004
L2.poil          -0.000365         0.000803           -0.455           0.649
L2.pmat           0.002361         0.002138            1.104           0.270
L2.pmetal        -0.000600         0.001285           -0.467           0.641
============================================================================

Results for equation poil
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const            -0.109018              NAN              NAN             NAN
const            -0.109018              NAN              NAN             NAN
ys                5.006210         1.021256            4.902           0.000
Dps               2.604490         1.864403            1.397           0.162
ys_lag1          -4.919034         1.006844           -4.886           0.000
Dps_lag1         -5.286709         1.874361           -2.821           0.005
L1.y              0.262693              NAN              NAN             NAN
L1.Dp            -1.065495         2.788220           -0.382           0.702
L1.eq             0.006746         0.177916            0.038           0.970
L1.r             -6.312233         8.332332           -0.758           0.449
L1.lr            16.506921        13.467341            1.226           0.220
L1.poil           0.961364         0.097592            9.851           0.000
L1.pmat           0.014343         0.266677            0.054           0.957
L1.pmetal         0.278447         0.151206            1.842           0.066
L2.y             -0.108544              NAN              NAN             NAN
L2.Dp             1.631393         2.318102            0.704           0.482
L2.eq            -0.111349         0.184207           -0.604           0.546
L2.r              9.311490         8.111525            1.148           0.251
L2.lr           -18.990272        12.978687           -1.463           0.143
L2.poil          -0.138210         0.097981           -1.411           0.158
L2.pmat          -0.205483         0.260868           -0.788           0.431
L2.pmetal        -0.092866         0.156700           -0.593           0.553
============================================================================

Results for equation pmat
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.140462              NAN              NAN             NAN
const             0.140462              NAN              NAN             NAN
ys                0.834767         0.362813            2.301           0.021
Dps               0.501765         0.662350            0.758           0.449
ys_lag1          -0.932380         0.357693           -2.607           0.009
Dps_lag1          0.355085         0.665888            0.533           0.594
L1.y              0.773636              NAN              NAN             NAN
L1.Dp             0.118826         0.990547            0.120           0.905
L1.eq             0.125853         0.063207            1.991           0.046
L1.r             -5.868728         2.960155           -1.983           0.047
L1.lr             0.857575         4.784425            0.179           0.858
L1.poil           0.002213         0.034671            0.064           0.949
L1.pmat           1.003126         0.094740           10.588           0.000
L1.pmetal         0.076841         0.053718            1.430           0.153
L2.y             -0.579819              NAN              NAN             NAN
L2.Dp            -0.486223         0.823532           -0.590           0.555
L2.eq            -0.161447         0.065441           -2.467           0.014
L2.r              5.894502         2.881711            2.045           0.041
L2.lr            -6.454278         4.610825           -1.400           0.162
L2.poil          -0.018486         0.034809           -0.531           0.595
L2.pmat          -0.147996         0.092676           -1.597           0.110
L2.pmetal        -0.047294         0.055670           -0.850           0.396
============================================================================

Results for equation pmetal
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const            -0.774281              NAN              NAN             NAN
const            -0.774281              NAN              NAN             NAN
ys                1.661432         0.600768            2.766           0.006
Dps               1.362074         1.096762            1.242           0.214
ys_lag1          -1.792826         0.592291           -3.027           0.002
Dps_lag1          1.184625         1.102620            1.074           0.283
L1.y              0.987720              NAN              NAN             NAN
L1.Dp            -1.227631         1.640210           -0.748           0.454
L1.eq             0.097950         0.104662            0.936           0.349
L1.r             -0.067116         4.901613           -0.014           0.989
L1.lr            -1.912546         7.922354           -0.241           0.809
L1.poil           0.011158         0.057410            0.194           0.846
L1.pmat          -0.044958         0.156876           -0.287           0.774
L1.pmetal         1.119941         0.088949           12.591           0.000
L2.y             -0.269444              NAN              NAN             NAN
L2.Dp             0.292254         1.363657            0.214           0.830
L2.eq            -0.241391         0.108362           -2.228           0.026
L2.r              4.288598         4.771720            0.899           0.369
L2.lr            -5.976089         7.634897           -0.783           0.434
L2.poil          -0.007431         0.057639           -0.129           0.897
L2.pmat          -0.049023         0.153459           -0.319           0.749
L2.pmetal        -0.209222         0.092181           -2.270           0.023
============================================================================

Correlation matrix of residuals
                 y        Dp        eq         r        lr      poil      pmat    pmetal
y         1.000000  0.019140  0.023788  0.252219  0.162197  0.046555 -0.100081 -0.053962
Dp        0.019140  1.000000 -0.021478  0.056104  0.242299  0.603674  0.202798  0.266003
eq        0.023788 -0.021478  1.000000  0.057142 -0.157503 -0.036446  0.062552  0.227348
r         0.252219  0.056104  0.057142  1.000000  0.594490  0.083855  0.110550  0.095323
lr        0.162197  0.242299 -0.157503  0.594490  1.000000  0.276274  0.281872  0.216764
poil      0.046555  0.603674 -0.036446  0.083855  0.276274  1.000000  0.269377  0.353001
pmat     -0.100081  0.202798  0.062552  0.110550  0.281872  0.269377  1.000000  0.349214
pmetal   -0.053962  0.266003  0.227348  0.095323  0.216764  0.353001  0.349214  1.000000

C:\Users\benchee\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\tsa\vector_ar\var_model.py:1558: RuntimeWarning: invalid value encountered in sqrt
  stderr = np.sqrt(np.diag(self.cov_params()))

# The code below is supposed to be a module to find the best lag order based on AIC, BIC and HQIC. 
# However, seeing that we need to see the results of the VECMX. I will get back to this when i can have a better picture on how the lags p, q = 2,2 works.

In [36]:
# this code block will be used for the AIC, BIC and HQIC

# define variables
exog_df = us_exog_df
endog_df = us_endog_df
#display(exog_df)
#print(f"endog_df is: \n {display(endog_df)}")

# Grid parameters
max_p = 3 # for domestic/ endog vars
max_q = 2 # for foreign/ exog vars
max_lag = max(max_p, max_q)

results = []

# 2. High level optimization loop using statsmodels internals. 
for p in range(1, max_p + 1):
    for q in range(0, max_q + 1):
        
        print(f"p,q are: ({p},{q})")
        # Construct foreign variables lag columns
        exog_list = []
        for lag in range(0, q + 1):
            print(f"lag (q) now is: {lag}")
            target_exog_df = exog_df.shift(lag)
            if lag >= 1:
                target_exog_df.columns = [f"{col}_lag{q}" for col in target_exog_df.columns]

            exog_list.append(target_exog_df) # shift the lag based on q variable.      
        
        X_exog = pd.concat(exog_list, axis = 1).dropna() # to concatenate by columns. 
#        print(f"X_exog is:\n {display(X_exog)}")
#        print(f"X_exog.index is:\n {display(X_exog.index)}")

        # Align endog target dataframe to match exogenous shift row losses.
        Y_target = endog_df.loc[X_exog.index]
#        print(f"Y_target is:\n {display(Y_target)}")

        # CRUCIAL GVAR TRIMMING: Ensure ALL lag combinations run on the exact same time window. 
        # This keeps the comparison mathematically fair across the loops. 
        X_exog_clean = X_exog.iloc[(max_lag - p):] # max_lag = 3, p = 1, ans = 2 
        Y_target_clean = Y_target.iloc[(max_lag - p):] # max_lag = 3, p = 1, ans = 2

#        print(f"X_exog_clean is:\n {display(X_exog_clean)}")
        print(f"X_exog_clean shape is:\n {(X_exog_clean.shape)}")
#        print(f"Y_target_clean is:\n {display(Y_target_clean)}")
        print(f"Y_target_clean shape is:\n {(Y_target_clean.shape)}")

        # 3. Call the built-in statsmodels VAR function with exog parameters
        # maxlags = p forces the engine to fit exactly 'p' for domestic lags
        model = VAR(endog = Y_target_clean, exog = X_exog_clean)
        results_fitted = model.fit(maxlags=p)

        # 4. Pull the native optimized AIC/BIC/HQIC calculations from the results object.
        results.append({
            'p' : p,
            'q' : q,
            'AIC' : results_fitted.aic,
            'BIC' : results_fitted.bic,
            'HQIC' : results_fitted.hqic,
        })
        
#        if q == 1: 
#            print(f"lets look at the results first.")
#            break

# 5. Display the final score sheet.
df_scores = pd.DataFrame(results)
print("--- Statsmodels Evaluated Scores ---")
print(f"df_scores is: \n {display(df_scores)}")
print(df_scores.to_string(index=False))

# Extract the winning combinations
print(f"\nWinning Architecture by AIC: P={df_scores.loc[df_scores['AIC'].idxmin(), 'p']}, Q = {df_scores.loc[df_scores['AIC'].idxmin(), 'q']}")
print(f"\nWinning Architecture by BIC: P={df_scores.loc[df_scores['BIC'].idxmin(), 'p']}, Q = {df_scores.loc[df_scores['BIC'].idxmin(), 'q']}")
print(f"\nWinning Architecture by HQIC: P={df_scores.loc[df_scores['HQIC'].idxmin(), 'p']}, Q = {df_scores.loc[df_scores['HQIC'].idxmin(), 'q']}")

p,q are: (1,0)
lag (q) now is: 0
X_exog_clean shape is:
 (176, 2)
Y_target_clean shape is:
 (176, 8)
p,q are: (1,1)
lag (q) now is: 0
lag (q) now is: 1
X_exog_clean shape is:
 (175, 4)
Y_target_clean shape is:
 (175, 8)
p,q are: (1,2)
lag (q) now is: 0
lag (q) now is: 1
lag (q) now is: 2
X_exog_clean shape is:
 (174, 6)
Y_target_clean shape is:
 (174, 8)
p,q are: (2,0)
lag (q) now is: 0
X_exog_clean shape is:
 (177, 2)
Y_target_clean shape is:
 (177, 8)
p,q are: (2,1)
lag (q) now is: 0
lag (q) now is: 1
X_exog_clean shape is:
 (176, 4)
Y_target_clean shape is:
 (176, 8)
p,q are: (2,2)
lag (q) now is: 0
lag (q) now is: 1
lag (q) now is: 2
X_exog_clean shape is:
 (175, 6)
Y_target_clean shape is:
 (175, 8)
p,q are: (3,0)
lag (q) now is: 0
X_exog_clean shape is:
 (178, 2)
Y_target_clean shape is:
 (178, 8)
p,q are: (3,1)
lag (q) now is: 0
lag (q) now is: 1
X_exog_clean shape is:
 (177, 4)
Y_target_clean shape is:
 (177, 8)
p,q are: (3,2)
lag (q) now is: 0
lag (q) now is: 1
lag (q) now is: 2
X_exog_clean shape is:
 (176, 6)
Y_target_clean shape is:
 (176, 8)
--- Statsmodels Evaluated Scores ---

   p  q        AIC        BIC       HQIC
0  1  0 -67.836095 -66.244659 -67.190563
1  1  1 -69.152206 -67.264035 -68.386248
2  1  2 -69.424765 -67.237511 -68.537409
3  2  0 -68.243021 -65.494179 -67.128013
4  2  1 -69.267610 -66.217488 -68.030293
5  2  2 -69.620710 -66.266920 -68.260098
6  3  0 -68.192103 -64.285853 -66.607616
7  3  1 -69.262275 -65.050201 -67.553599
8  3  2 -69.663047 -65.142721 -67.829178

df_scores is:
 None
 p  q        AIC        BIC       HQIC
 1  0 -67.836095 -66.244659 -67.190563
 1  1 -69.152206 -67.264035 -68.386248
 1  2 -69.424765 -67.237511 -68.537409
 2  0 -68.243021 -65.494179 -67.128013
 2  1 -69.267610 -66.217488 -68.030293
 2  2 -69.620710 -66.266920 -68.260098
 3  0 -68.192103 -64.285853 -66.607616
 3  1 -69.262275 -65.050201 -67.553599
 3  2 -69.663047 -65.142721 -67.829178

Winning Architecture by AIC: P=3, Q = 2

Winning Architecture by BIC: P=1, Q = 1

Winning Architecture by HQIC: P=1, Q = 2